 version: 2
 jobs:
   one:
     steps:
       - checkout
       - run: npm run-script build
       - aws-s3/sync:
          from: build
          to: 's3://terraform-alex-shing'
          overwrite: true
